name: 'Your Action Name'
description: 'Your action description'
author: Your name or organization here

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  milliseconds:
    description: 'Number of milliseconds to wait'
    required: true
    default: '1000'

# Define your outputs here.
outputs:
  time:
    description: 'The current time after waiting'

runs:
  using: 'node20'
  main: 'packages/action/dist/index.js'
